### POST Crear nuevo comercio
POST http://localhost:3000/api/comerce
Content-Type: application/json

{
    "Nombre_del_comercio": "Mi Comercio",
    "CIF": 12345678,
    "password": "miPasswordSeguro",
    "email": "comercio@example.com",
    "Teléfono_de_contacto": 123456789
}

###
POST http://localhost:3000/api/comerce
Content-Type: application/json

{
    "Nombre_del_comercio": "Mi Comercio3",
    "CIF": 87654321,
    "password": "miPa3sswordSeguro",
    "email": "comercio3@example3.com",
    "Teléfono_de_contacto": 12345678935
}
###

DELETE http://localhost:3000/api/comerce/670ea1b76fd5326329866518

###
GET http://localhost:3000/api/comerce/670e8f7edc962dccacefe7a6

###
PUT http://localhost:3000/api/comerce/670e8f7edc962dccacefe7a6
Content-Type: application/json

{
    "Nombre_del_comercio": "Mi Comercio2",
    "CIF": 87654321,
    "password": "miPa2sswordSeguro",
    "email": "nuevoemail@example.com",
    "Teléfono_de_contacto": 123456789
}

###
GET http://localhost:3000/api/comerce

###
PUT  http://localhost:3000/api/comerce/cif/87654321
Content-Type: application/json

{
    "Nombre_del_comercio": "Mi Comercio2con nuevo cip",
    "CIF": 87654321,
    "password": "miPa2sswordSeguro",
    "email": "nuevoemaill@example.com",
    "Telefono_de_contacto": 123456789
}

###
GET http://localhost:3000/api/comerce/cif/87654321

###
DELETE http://localhost:3000/api/comerce/cif/87654321

###
GET http://localhost:3000/api/comerce/ciforder

###

POST http://localhost:3000/api/comerceDetailsRoutes
Content-Type: application/json

{
    "Ciudad": "Madrid",
    "Actividad": "Venta de Ropa",
    "Título": "Tienda de Ropa noderna",
    "Resumen": "Ofrecemos una amplia variedad de ropa moderna y a la moda.",
    "textos": ["Texto descriptivo 1", "Texto descriptivo 2"],
    "imágenes": ["imagen1.jpg", "imagen2.jpg"],
    "reseñasUsuarios": {
        "scoring": 4.5,
        "numeroPuntuacionesTotales": 10,
        "reseñas": ["Excelente servicio", "Buena calidad"]
    },
    "isArchived": false
}


###

DELETE  http://localhost:3000/api/comerceDetailsRoutes/6717db086ef0284c5cab1747


###

PUT http://localhost:3000/api/comerceDetailsRoutes/6717dba5255a273b8c0b0dbe
Content-Type: application/json

{
    "Ciudad": "Madrid",
    "Actividad": "Venta de Ropa",
    "Título": "Tienda de Ropa moderna",
    "Resumen": "Ofrecemos una amplia variedad de ropa moderna y a la moda.",
    "textos": ["Texto descriptivo 1", "Texto descriptivo 2"],
    "imágenes": ["imagen1.jpg", "imagen2.jpg"],
    "reseñasUsuarios": {
        "scoring": 4.5,
        "numeroPuntuacionesTotales": 10,
        "reseñas": ["Excelente servicio", "Buena calidad"]
    },
    "isArchived": false
}

###
GET http://localhost:3000/api/comerceDetailsRoutes/6717dba5255a273b8c0b0dbe

###
PATCH  http://localhost:3000/api/comerceDetailsRoutes/6717dba5255a273b8c0b0dbe/archive



###

POST http://localhost:3000/api/userRoutes/users
Content-Type: application/json

{
    "Nombre": "Juan Pérez",
    "email": "juanperez@gmail.com",
    "Password": "password123",
    "Edad": 30,
    "Ciudad": "Madrid",
    "Intereses": ["Deportes", "Música", "Viajes"],
    "PermiteRecibirOfertas": true,
    "Role": "user"
}